services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: lapak
      POSTGRES_PASSWORD: lapak
      POSTGRES_DB: lapak
    ports:
      - "5432:5432"
    volumes:
      - lapak_db_data:/var/lib/postgresql/data

volumes:
  lapak_db_data:
